### ISSUE TITLE
No Content Deployed

### ISSUE THREAD

**Issue by fatpacket** [FBoucher/TinyBlazorAdmin#94]
Recently installed URL Shortner and TinyBlazorAdmin.  When I hit the SWA link i get a page the my web app is live but we dont have any content udpdates.  I followed the instruction with the one step of not being able to add an invite because it again said I needed to have a deployment before I could send an invite.
I am not sure what I am missing.  the URLShortner test redirect via api worked just fine..

**Comment by FBoucher** [comment]
Thank you @fatpacket we will review the docs and make sure everything works.

**Comment by ilayn** [comment]
Just hit the same problem. Randomly adding endpoints I found in `/src/client/staticwebapp.config.json` to the URL, triggered the app and I was able to have the invite button clickable.

**Comment by FBoucher** [comment]
@all-contributors add @fatpacket for doc

**Comment by FBoucher** [comment]
@ilayn you must go in the Azure portal to create invites. Send the generated URL to the person (or used it if you are trying to add yourself). When the person clicks on the generated URL it will request to Grant access, then redirect to your TinyBlazor Admin website.

What did you edit in the config file?

**Comment by ilayn** [comment]
My apologies for being a bit terse. Let me clarify. I hit the same no content available problem as @fatpacket. To trigger an active development for the SWA  I've tried to access `<app url>/urlmanager` even though we don't have any active logins. 

That actually triggered the app to run and only then the Invite link became available on the Azure side Role Management tab. Otherwise it is a chicken/egg problem since one waits for the app to come online to login but on the other hand invite link only becomes active once the app is fully functional.

Hence I didn't do any edits but forced an endpoint to render to make Azure think that it is alive. 

After that I generated an invite link and followed the instructions on an incognito window but probably because my user is not an owner priviledged user in the Azure subscription the request ends with "Request is sent for approval". And then I don't know what happens to the request. 

Note that I've done all this experiment to create two tables missing from the Azure Storage Explorer, and I think we can improve on this without going through all the Azure Role Management hassle by auto pushing a generic user at the app setup.

**Comment by FBoucher** [comment]
@ilayn you don't have to create the tables they will be created by the code.
Once the deployment of TinyBlazorAdmin is done (by that I mean the GitHub Action deployed successfully) you need to create the user with the invite. To keep the solution easy to deploy and budget-friendly, the native Azure Static WebApp authentication is used.

The API is not available from outside the Static WebApp. It is not possible to create links outside TinyBlazorAdmin.

**Comment by ilayn** [comment]
Yes, that is correct. But the tables are only created if there is the initial request as I understood from https://github.com/FBoucher/AzUrlShortener/issues/441#issuecomment-1339669373 when there is an initial hit. 

But to create that initial hit we need to have some machinery to do that. From a discussion I read that you recommend this frontend. And this frontend needs a user login. For that we need the Azure Role management step which didn't go through for me. So all these efforts to make the tables created. 

I guess what I am trying to say is that if the tables were created already with a dummy user enabled, it would not be necessary to have the blazor admin in the first place because I don't intend to use it and plan to manage things from the Azure Storage Explorer but currently there is a strong coupling with the blazor admin to make use of url shortener.

**Comment by FBoucher** [comment]
If you just want to use the AzUrlShortener with Azure Storage Explorer, you don't need any user.

With the Storage explorer, open the table link shown [here](https://github.com/FBoucher/AzUrlShortener/wiki/How-to-Use-Azure-Storage-Explorer-as-Admin-Tools-for-AzUrlShortener#create-a-new-short-url) and create a record with the following: 

- Partition key: (Required) This MUST be the first character of your short URL (aka RowKey).
- RowKey: (Required) The short URL.
- Url: (Required) The original (aka long) URL.
- Title: (Optional) This is for your convenience. Write something that helps you understand what the URL is from.
- Is Archived: (Optional) Since we create a new URL leaves that field empty.

> Note: Partition key and RowKey are case-sensitive.

I will write something to create a single short URL with a script or something.

**Comment by ilayn** [comment]
Ah yes. The part I'm stuck with is that I don't have those two tables including UrlsDetails

**Comment by FBoucher** [comment]
@ilayn Now that I understand better let's close this issue since it's more AzUrlShortener related.
I re-open [Missing URL tables #441(]https://github.com/FBoucher/AzUrlShortener/issues/441) let's continue over there
